-- AlterTable
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "overtimeThreshold" TEXT;
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "halfDayRate" DECIMAL(14,2);
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "minimumQuantity" DECIMAL(14,2);
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "netsuiteItem" TEXT;
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "appliesTo" TEXT;
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "appliesToWells" JSONB;
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "approvalStatus" TEXT;
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "approvedBy" TEXT;
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
