ALTER TABLE "CrmSyncState" ADD COLUMN IF NOT EXISTS "targetActivities" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "CrmSyncState" ADD COLUMN IF NOT EXISTS "targetCalls" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "CrmSyncState" ADD COLUMN IF NOT EXISTS "targetVisits" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "CrmSyncState" ADD COLUMN IF NOT EXISTS "targetQuotes" INTEGER NOT NULL DEFAULT 6;
ALTER TABLE "CrmSyncState" ADD COLUMN IF NOT EXISTS "targetPipeline" DECIMAL(14,2) NOT NULL DEFAULT 150000;
ALTER TABLE "CrmSyncState" ADD COLUMN IF NOT EXISTS "targetEodPct" INTEGER NOT NULL DEFAULT 100;
