-- Full Add Form Rule fields
ALTER TABLE "FormRule" ADD COLUMN IF NOT EXISTS "appliesToEnd" TIMESTAMP(3);
ALTER TABLE "FormRule" ADD COLUMN IF NOT EXISTS "scope" TEXT;
ALTER TABLE "FormRule" ADD COLUMN IF NOT EXISTS "versionMode" TEXT;
ALTER TABLE "FormRule" ADD COLUMN IF NOT EXISTS "overrideRoles" JSONB;
ALTER TABLE "FormRule" ADD COLUMN IF NOT EXISTS "requireOverrideReason" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "FormRule" ADD COLUMN IF NOT EXISTS "rolloutMode" TEXT;
