-- AlterEnum
DO $$ BEGIN
  ALTER TYPE "ExpenseStatus" ADD VALUE 'NEEDS_REVIEW';
EXCEPTION
  WHEN duplicate_object THEN null;
  WHEN others THEN null;
END $$;

ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "reimbursable" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptFileName" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptFileSizeBytes" INTEGER;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptCaptureMethod" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptLat" DOUBLE PRECISION;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptLng" DOUBLE PRECISION;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptCapturedAt" TIMESTAMP(3);
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "flaggedAt" TIMESTAMP(3);
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
